import {useEffect,useRef,useState} from 'react';
import {ArrowUpRight,Undo2,Lightbulb,Grid2X2,Leaf,ShieldCheck,BookOpen,ChevronLeft,ChevronRight,Download,Upload,Plus,Trash2,Pencil,Check} from 'lucide-react';
import {Board} from './components/Board';import {Modal} from './components/Modal';
import {moves,play,score,coord} from './game/engine';import type {Side} from './game/engine';
import {load,save,createMatch,validate} from './game/storage';import type {Data,Match} from './game/storage';
import {dictionaries,languages} from './i18n';import type {Lang} from './i18n';import './App.css';
export default function App(){
 const [data,setData]=useState(load);const [page,setPage]=useState('play');const [modal,setModal]=useState<'rules'|'new'|'delete'|'clear'|null>(null);const [deleteId,setDeleteId]=useState('');const [storageOK,setStorageOK]=useState(true);const [notice,setNotice]=useState('');const [mode,setMode]=useState<'ai'|'local'>(data.current.mode);const [level,setLevel]=useState(data.current.level);const [human,setHuman]=useState<Side>(data.current.human);const [player,setPlayer]=useState(data.profiles[0].id);const [opponent,setOpponent]=useState(data.profiles[1]?.id||'');const [show,setShow]=useState(true);const [hint,setHint]=useState<number|null>(null);const [hintRequest,setHintRequest]=useState(false);const [aiError,setAiError]=useState(false);const [retry,setRetry]=useState(0);const [name,setName]=useState('');const [edit,setEdit]=useState<string|null>(null);const [replay,setReplay]=useState<Match|null>(null);const [step,setStep]=useState(0);const [filter,setFilter]=useState('all');const upload=useRef<HTMLInputElement>(null);
 const lang:Lang=data.lang in dictionaries?data.lang as Lang:'en',t=dictionaries[lang];const game=data.current,s=game.positions.at(-1)!,count=score(s.board),legal=moves(s.board,s.turn);const aiTurn=game.mode==='ai'&&s.turn!==game.human&&!s.over;const busy=aiTurn||hintRequest;const blackName=game.black==='ai'?'MindDev25 AI':game.blackName,whiteName=game.white==='ai'?'MindDev25 AI':game.whiteName;
 // Persisting browser state is the external synchronization performed by this effect.
 // oxlint-disable-next-line react-hooks/set-state-in-effect
 useEffect(()=>{setStorageOK(save(data));document.documentElement.lang=lang;},[data,lang]);
 useEffect(()=>{if(!aiTurn&&!hintRequest)return;const worker=new Worker(new URL('./game/ai.worker.ts',import.meta.url),{type:'module'});const id=game.id,len=game.positions.length;let alive=true;const timer=setTimeout(()=>worker.postMessage({board:s.board,side:s.turn,level:hintRequest?8:game.level}),200);worker.onmessage=({data:r})=>{if(!alive)return;if(r.error||r.move===null){setAiError(true);setHintRequest(false);return;}if(hintRequest){setHint(r.move);setHintRequest(false);setNotice(t.hintNote);setData(d=>({...d,current:{...d.current,assisted:true}}));}else setData(d=>{if(d.current.id!==id||d.current.positions.length!==len)return d;const next=play(d.current.positions.at(-1)!,r.move);const current={...d.current,positions:[...d.current.positions,next]};return{...d,current,history:next.over?[current,...d.history.filter(h=>h.id!==id)].slice(0,200):d.history};});};worker.onerror=()=>{setAiError(true);setHintRequest(false);};return()=>{alive=false;clearTimeout(timer);worker.terminate();};},[aiTurn,hintRequest,game.id,game.positions.length,game.level,s,retry,t.hintNote]);
 function move(i:number){if(busy||s.over)return;const next=play(s,i),current={...game,positions:[...game.positions,next]};setHint(null);setNotice('');setAiError(false);setData(d=>({...d,current,history:next.over?[current,...d.history.filter(h=>h.id!==current.id)].slice(0,200):d.history}));}
 function start(){const p=data.profiles.find(p=>p.id===player)||data.profiles[0];const o=data.profiles.find(x=>x.id===opponent&&x.id!==p.id)||data.profiles.find(x=>x.id!==p.id);if(mode==='local'&&!o)return;const black=mode==='ai'&&human===-1?'ai':p.id;const white=mode==='ai'?(human===1?'ai':p.id):o!.id;setData(d=>({...d,current:createMatch(mode,level,human,black,white,black==='ai'?'MindDev25 AI':p.name,white==='ai'?'MindDev25 AI':mode==='ai'?p.name:o!.name)}));setHint(null);setHintRequest(false);setAiError(false);setNotice('');setModal(null);setPage('play');}
 function undo(){if(game.positions.length<2||s.over)return;let n=game.positions.length-2;if(game.mode==='ai')while(n>0&&game.positions[n].turn!==game.human)n--;setData(d=>({...d,current:{...d.current,positions:d.current.positions.slice(0,n+1),assisted:true}}));setHintRequest(false);setHint(null);setNotice(t.hintNote);}
 function profileSave(){const clean=name.trim();if(!clean)return;setData(d=>({...d,profiles:edit?d.profiles.map(p=>p.id===edit?{...p,name:clean}:p):[...d.profiles,{id:crypto.randomUUID(),name:clean,color:['#d8775d','#688875','#a88bba','#b3925e'][d.profiles.length%4]}]}));setName('');setEdit(null);}
 function exportData(){const a=document.createElement('a'),url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.href=url;a.download='minddev25-reversi-backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setNotice(t.downloaded);}
 async function importData(file?:File){if(!file)return;try{if(file.size>10_000_000)throw Error();const value:Data=JSON.parse(await file.text());if(!validate(value))throw Error();if(confirm(t.importConfirm)){setData(value);setPlayer(value.profiles[0].id);setOpponent(value.profiles[1]?.id||'');setMode(value.current.mode);setLevel(value.current.level);setHuman(value.current.human);setReplay(null);setHint(null);setHintRequest(false);setNotice('');}}catch{setNotice(t.invalid);}if(upload.current)upload.current.value='';}
 const result=s.over?(count.black===count.white?t.draw:`${count.black>count.white?blackName:whiteName} ${t.wins}`):aiTurn?t.thinking:`${s.turn===1?blackName:whiteName} ${t.turn}`;
 return <div className="app"><header><a className="brand" href="#" onClick={e=>{e.preventDefault();setPage('play');}}>MindDev25 Reversi<span className="brand-dot"/></a><nav>{(['play','players','history'] as const).map(p=><button key={p} className={page===p?'active':''} onClick={()=>{setPage(p);setReplay(null);setNotice('');}}>{t[p]}</button>)}</nav><select aria-label="Language" value={lang} onChange={e=>setData(d=>({...d,lang:e.target.value}))}>{Object.entries(languages).map(([k,v])=><option value={k} key={k}>{v}</option>)}</select></header>
 {!storageOK&&<div className="warning" role="alert">{t.storageError}</div>}
 {page==='play'?<><section className="intro"><h1>{t.title}</h1><p>{t.subtitle}</p></section><main className="game-layout"><section className="table"><div className="scoreboard"><div className={`score-player ${s.turn===1&&!s.over?'current':''}`}><span className="mini-disc dark"/><div><span>{blackName}</span><strong>{String(count.black).padStart(2,'0')}</strong></div></div><div className="turn-status" role="status"><span>{s.over?t.finished:result}</span><span className={`status-dot ${busy?'pulse':''}`}/></div><div className={`score-player right ${s.turn===-1&&!s.over?'current':''}`}><div><span>{whiteName}</span><strong>{String(count.white).padStart(2,'0')}</strong></div><span className="mini-disc light"/></div></div><Board position={s} legal={s.over?[]:legal} hint={hint} onMove={busy||s.over?undefined:move} show={show} t={t}/><div className="board-tools"><button onClick={undo} disabled={game.positions.length<2||s.over}><Undo2/>{t.undo}</button><button onClick={()=>{setHintRequest(true);setHint(null);}} disabled={busy||s.over}><Lightbulb/>{t.hint}</button><button aria-pressed={show} onClick={()=>setShow(!show)}><Grid2X2/>{t.showMoves}</button></div><div className="board-message" aria-live="polite">{s.over?<><strong>{result}</strong><button onClick={()=>{setReplay(game);setStep(0);setPage('history');}}>{t.replay}<ArrowUpRight size={16}/></button></>:s.passed?t.pass:game.assisted?t.assisted:`${game.positions.length-1} / 60 ${t.moves}`}{aiError&&<button onClick={()=>setRetry(x=>x+1)}>{t.aiError} {t.retry}</button>}</div></section>
 <aside className="setup"><h2><Leaf size={24}/>{t.newGame}</h2><div className="segmented">{(['ai','local'] as const).map(m=><button key={m} aria-pressed={mode===m} className={mode===m?'selected':''} onClick={()=>setMode(m)}>{t[m]}</button>)}</div><label>{t.player}<select value={player} onChange={e=>setPlayer(e.target.value)}>{data.profiles.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label>{mode==='local'?<label>{t.opponent}<select value={opponent===player?(data.profiles.find(p=>p.id!==player)?.id||''):opponent} onChange={e=>setOpponent(e.target.value)}>{data.profiles.filter(p=>p.id!==player).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select>{data.profiles.length<2&&<small>{t.noOpponent}</small>}</label>:<fieldset><legend>{t.side}</legend><label className="radio"><input type="radio" name="side" checked={human===1} onChange={()=>setHuman(1)}/>{t.black}<small>({t.starts})</small></label><label className="radio"><input type="radio" name="side" checked={human===-1} onChange={()=>setHuman(-1)}/>{t.white}</label></fieldset>}
 {mode==='ai'&&<div className="difficulty"><div><label htmlFor="difficulty">{t.difficulty}</label><strong>{String(level).padStart(2,'0')}<span> / 10</span></strong></div><input id="difficulty" type="range" min="1" max="10" value={level} onChange={e=>setLevel(+e.target.value)}/><div className="range-labels"><span>{t.beginner}</span><span>{t.expert}</span></div><p>{t.aiNote}</p></div>}<button className="primary" disabled={mode==='local'&&data.profiles.length<2} onClick={()=>game.positions.length>1&&!s.over?setModal('new'):start()}>{t.start}<ArrowUpRight size={18}/></button><p className="local-note">{t.localNote}</p><button className="rules-link" onClick={()=>setModal('rules')}><BookOpen size={17}/>{t.rules}</button></aside></main></>:
 page==='players'?<main className="content-page"><div className="page-heading"><h1>{t.profilesTitle}</h1><p>{t.profilesNote}</p></div><div className="profiles">{data.profiles.map(p=>{const games=data.history.filter(g=>!g.assisted&&(g.black===p.id||g.white===p.id));const wins=games.filter(g=>{const c=score(g.positions.at(-1)!.board);return g.black===p.id?c.black>c.white:c.white>c.black;}).length;return <article className="profile" key={p.id}><span className="avatar" style={{background:p.color}}>{p.name.slice(0,1).toUpperCase()}</span><div className="profile-info"><h2>{p.name}</h2><div className="stats"><span><b>{games.length}</b>{t.games}</span><span><b>{wins}</b>{t.won}</span><span><b>{games.length?Math.round(wins/games.length*100):0}%</b>{t.winRate}</span></div></div><div className="profile-actions"><button aria-label={`${t.rename} ${p.name}`} onClick={()=>{setEdit(p.id);setName(p.name);}}><Pencil size={17}/></button><button aria-label={`${t.remove} ${p.name}`} disabled={data.profiles.length===1} onClick={()=>{setDeleteId(p.id);setModal('delete');}}><Trash2 size={17}/></button></div></article>;})}</div><form className="profile-form" onSubmit={e=>{e.preventDefault();profileSave();}}><label>{t.name}<input maxLength={30} value={name} onChange={e=>setName(e.target.value)} required/></label><button className="primary" disabled={!name.trim()||(!edit&&data.profiles.length>=30)}>{edit?<Check size={18}/>:<Plus size={18}/>} {edit?t.save:t.add}</button>{edit&&<button type="button" onClick={()=>{setEdit(null);setName('');}}>{t.cancel}</button>}</form><p className="muted">{t.practiceNote}</p><div className="backup"><p>{t.backupNote}</p><button onClick={exportData}><Download/>{t.export}</button><button onClick={()=>upload.current?.click()}><Upload/>{t.import}</button><input ref={upload} hidden type="file" accept="application/json,.json" onChange={e=>importData(e.target.files?.[0])}/></div></main>:
 <main className="content-page"><div className="page-heading"><h1>{t.historyTitle}</h1><p>{t.replayNote}</p></div>{replay?<div className="replay"><button onClick={()=>setReplay(null)}><ChevronLeft/>{t.back}</button><div className="replay-heading"><h2>{replay.blackName} <span>·</span> {replay.whiteName}</h2><p>{t.step} {step} / {replay.positions.length-1}{step>0&&` · ${coord(replay.positions[step].move!)}`}</p></div><Board position={replay.positions[step]} t={t} show={false}/><div className="replay-controls"><button aria-label={t.back} disabled={step===0} onClick={()=>setStep(x=>x-1)}><ChevronLeft/></button><input aria-label={t.step} type="range" min={0} max={replay.positions.length-1} value={step} onChange={e=>setStep(+e.target.value)}/><button aria-label={t.step} disabled={step===replay.positions.length-1} onClick={()=>setStep(x=>x+1)}><ChevronRight/></button></div></div>:<><div className="history-toolbar"><select aria-label={t.player} value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">{t.all}</option>{data.profiles.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><button disabled={!data.history.length} onClick={()=>setModal('clear')}><Trash2 size={16}/>{t.deleteHistory}</button></div>{!data.history.filter(g=>filter==='all'||g.black===filter||g.white===filter).length?<div className="empty-state"><div className="empty-discs"><span className="mini-disc dark"/><span className="mini-disc light"/></div><h2>{t.empty}</h2><p>{t.emptyNote}</p><button className="primary" onClick={()=>setPage('play')}>{t.resume}<ArrowUpRight size={18}/></button></div>:<div className="history-list">{data.history.filter(g=>filter==='all'||g.black===filter||g.white===filter).map(g=>{const c=score(g.positions.at(-1)!.board);return <button className="history-row" key={g.id} onClick={()=>{setReplay(g);setStep(0);}}><span className="history-icon"><Leaf/></span><span><strong>{g.blackName} <span>·</span> {g.whiteName}</strong><small>{new Date(g.date).toLocaleString(lang)} · {g.mode==='ai'?`${t.level} ${g.level}`:t.local}{g.assisted?` · ${t.assisted}`:''}</small></span><b>{c.black} – {c.white}</b><ChevronRight size={18}/></button>;})}</div>}</>}</main>}
 {notice&&<div className="notice" role="status">{notice}<button aria-label={t.close} onClick={()=>setNotice('')}>×</button></div>}<footer><ShieldCheck size={20}/><span>{t.privacy}</span><span className="footer-name">MindDev25 · Reversi</span></footer>
 {modal&&<Modal title={modal==='rules'?t.rulesTitle:modal==='new'?t.replace:modal==='delete'?t.deleteTitle:t.clearConfirm} close={()=>setModal(null)} label={t.close}>{modal==='rules'?<div className="rules"><ol><li>{t.rule1}</li><li>{t.rule2}</li><li>{t.rule3}</li></ol><p className="tip"><Lightbulb size={20}/>{t.tip}</p></div>:<><p>{modal==='new'?t.replaceNote:modal==='delete'?t.deleteNote:t.clearConfirm}</p><div className="modal-actions"><button onClick={()=>setModal(null)}>{t.cancel}</button><button className="primary" onClick={()=>{if(modal==='new')start();else if(modal==='clear'){setData(d=>({...d,history:[]}));setModal(null);}else{const profiles=data.profiles.filter(p=>p.id!==deleteId);setData(d=>({...d,profiles}));setPlayer(profiles[0].id);setOpponent(profiles[1]?.id||'');setModal(null);}}}>{modal==='new'?t.confirm:t.remove}</button></div></>}</Modal>}
 </div>;
}
