import {ArrowRight,Gamepad2,Hammer,Palette,ShieldCheck,Sparkles} from 'lucide-react';
import './Home.css';
const gameUrl='/minddev25_apps/minddev25_reversi/';
export default function Home(){return <div className="home-shell">
 <div className="home-nav"><a className="home-logo" href="/minddev25_apps/">MindDev25<span/></a><nav aria-label="Categories"><a href="#games">Games</a><a href="#tools">Tools</a><a href="#creative">Creative</a></nav><a className="home-github" href="https://github.com/minddev25/minddev25_apps">GitHub <ArrowRight size={15}/></a></div>
 <main><section className="home-hero"><p className="home-eyebrow"><Sparkles size={15}/> SMALL APPS, BRIGHT IDEAS</p><h1>Useful little things,<br/><em>thoughtfully made.</em></h1><p className="home-lead">A growing collection of focused browser apps and games. Private by default, quick to open, and made to feel good.</p><a className="home-cta" href="#games">Explore the collection <ArrowRight size={17}/></a><div className="hero-orbit" aria-hidden="true"><span/><span/><span/></div></section>
 <section className="collection" id="games"><div className="section-heading"><div><p>01 / GAMES</p><h2>Play for a moment.<br/>Think for a while.</h2></div><Gamepad2 size={31}/></div><a className="app-tile" href={gameUrl}><div className="tile-art" aria-hidden="true"><div className="mini-board">{Array.from({length:16},(_,i)=><span key={i} className={i===5||i===10?'stone light-stone':i===6||i===9?'stone dark-stone':''}/>)}</div></div><div className="tile-copy"><div className="tile-meta"><span>GAME · STRATEGY</span><span>4 LANGUAGES</span></div><h3>MindDev25 Reversi</h3><p>A calm, modern take on the classic board game. Challenge ten levels of local AI or share the board with a friend.</p><div className="tile-link">Play now <ArrowRight size={18}/></div></div></a></section>
 <section className="coming-grid"><article id="tools"><Hammer/><span>02 / TOOLS</span><h2>Small helpers<br/>for everyday work.</h2><p>New tools are being shaped.</p></article><article id="creative"><Palette/><span>03 / CREATIVE</span><h2>Room to make<br/>and experiment.</h2><p>Creative apps are coming next.</p></article></section></main>
 <footer className="home-footer"><ShieldCheck size={18}/><span>Frontend only · No tracking · Your data stays in your browser</span><b>MindDev25 © 2026</b></footer>
 </div>}
