import {useEffect,useState} from 'react';
import {ArrowRight,Gamepad2,Hammer,Palette,ShieldCheck,Sparkles} from 'lucide-react';
import {languages} from './i18n';import type {Lang} from './i18n';
import {load,save} from './game/storage';
import './Home.css';
const gameUrl='/minddev25_apps/minddev25_reversi/';
const copy={
 en:{pageTitle:'MindDev25 Apps — Small ideas, thoughtfully made',categories:'Categories',games:'Games',tools:'Tools',creative:'Creative',eyebrow:'SMALL APPS, BRIGHT IDEAS',title:<>Useful little things,<br/><em>thoughtfully made.</em></>,lead:'A growing collection of focused browser apps and games. Private by default, quick to open, and made to feel good.',explore:'Explore the collection',gameHeading:<>Play for a moment.<br/>Think for a while.</>,meta:'GAME · STRATEGY',langs:'4 LANGUAGES',description:'A calm, modern take on the classic board game. Challenge ten levels of local AI or share the board with a friend.',play:'Play now',toolsHeading:<>Small helpers<br/>for everyday work.</>,toolsNote:'New tools are being shaped.',creativeHeading:<>Room to make<br/>and experiment.</>,creativeNote:'Creative apps are coming next.',privacy:'Frontend only · No tracking · Your data stays in your browser'},
 ja:{pageTitle:'MindDev25 Apps — 小さなアイデアを丁寧に',categories:'カテゴリー',games:'ゲーム',tools:'ツール',creative:'クリエイティブ',eyebrow:'小さなアプリ、明るいアイデア',title:<>日々に役立つ小さなものを、<br/><em>丁寧につくる。</em></>,lead:'目的をひとつに絞った、ブラウザーで使えるアプリとゲーム。すぐに開けて、データはあなたの端末に。',explore:'コレクションを見る',gameHeading:<>少し遊んで、<br/>じっくり考える。</>,meta:'ゲーム · ストラテジー',langs:'4言語対応',description:'クラシックなボードゲームを、静かでモダンに。10段階のローカルAI、または友だちとの対局を楽しめます。',play:'今すぐ遊ぶ',toolsHeading:<>毎日のための、<br/>小さな便利ツール。</>,toolsNote:'新しいツールを準備中です。',creativeHeading:<>つくる、試す、<br/>楽しむ場所。</>,creativeNote:'クリエイティブアプリも近日公開。',privacy:'フロントエンドのみ · 追跡なし · データはブラウザーに保存'},
 zh:{pageTitle:'MindDev25 应用 — 用心打造的小应用',categories:'分类',games:'游戏',tools:'工具',creative:'创意',eyebrow:'小巧应用，闪亮灵感',title:<>实用的小应用，<br/><em>用心做好每一个。</em></>,lead:'持续收录专注、好用的浏览器应用与游戏。打开即用，默认保护隐私，操作舒适自然。',explore:'浏览应用合集',gameHeading:<>玩一会儿，<br/>思考久一点。</>,meta:'游戏 · 策略',langs:'支持4种语言',description:'安静、现代的经典棋盘游戏。挑战十个等级的本地 AI，或与朋友共享棋盘对弈。',play:'立即开始',toolsHeading:<>为日常工作准备的<br/>小巧助手。</>,toolsNote:'更多实用工具正在制作中。',creativeHeading:<>自由创作，<br/>尽情尝试。</>,creativeNote:'创意应用即将推出。',privacy:'纯前端 · 无追踪 · 数据保存在你的浏览器中'},
 ko:{pageTitle:'MindDev25 Apps — 작은 아이디어를 정성껏',categories:'카테고리',games:'게임',tools:'도구',creative:'크리에이티브',eyebrow:'작은 앱, 빛나는 아이디어',title:<>쓸모 있는 작은 것들을,<br/><em>정성껏 만듭니다.</em></>,lead:'한 가지 목적에 집중한 브라우저 앱과 게임 모음입니다. 바로 열고, 편안하게 쓰며, 데이터는 내 기기에 보관하세요.',explore:'컬렉션 둘러보기',gameHeading:<>잠시 즐기고,<br/>오래 생각하세요.</>,meta:'게임 · 전략',langs:'4개 언어',description:'고전 보드게임을 차분하고 현대적으로 즐겨보세요. 10단계 로컬 AI에 도전하거나 친구와 함께 둘 수 있습니다.',play:'지금 플레이',toolsHeading:<>일상을 돕는<br/>작은 도구들.</>,toolsNote:'새로운 도구를 준비하고 있습니다.',creativeHeading:<>만들고 실험하는<br/>즐거운 공간.</>,creativeNote:'크리에이티브 앱도 곧 공개됩니다.',privacy:'프론트엔드 전용 · 추적 없음 · 데이터는 브라우저에 저장'}
} satisfies Record<Lang,Record<string,string|React.ReactNode>>;
export default function Home(){const initial=load().lang;const [lang,setLang]=useState<Lang>(initial in languages?initial as Lang:'en');const t=copy[lang];useEffect(()=>{document.documentElement.lang=lang;document.title=copy[lang].pageTitle as string;const sync=()=>{const value=load().lang;if(value in languages)setLang(value as Lang)};addEventListener('storage',sync);return()=>removeEventListener('storage',sync)},[lang]);function choose(value:Lang){setLang(value);const data=load();save({...data,lang:value})}return <div className="home-shell">
 <div className="home-nav"><a className="home-logo" href="/minddev25_apps/">MindDev25<span/></a><nav aria-label={t.categories as string}><a href="#games">{t.games}</a><a href="#tools">{t.tools}</a><a href="#creative">{t.creative}</a></nav><select className="home-language" aria-label="Language" value={lang} onChange={e=>choose(e.target.value as Lang)}>{Object.entries(languages).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select><a className="home-github" href="https://github.com/minddev25/minddev25_apps">GitHub <ArrowRight size={15}/></a></div>
 <main><section className="home-hero"><p className="home-eyebrow"><Sparkles size={15}/> {t.eyebrow}</p><h1>{t.title}</h1><p className="home-lead">{t.lead}</p><a className="home-cta" href="#games">{t.explore} <ArrowRight size={17}/></a><div className="hero-orbit" aria-hidden="true"><span/><span/><span/></div></section>
 <section className="collection" id="games"><div className="section-heading"><div><p>01 / {t.games}</p><h2>{t.gameHeading}</h2></div><Gamepad2 size={31}/></div><a className="app-tile" href={gameUrl}><div className="tile-art" aria-hidden="true"><div className="mini-board">{Array.from({length:16},(_,i)=><span key={i} className={i===5||i===10?'stone light-stone':i===6||i===9?'stone dark-stone':''}/>)}</div></div><div className="tile-copy"><div className="tile-meta"><span>{t.meta}</span><span>{t.langs}</span></div><h3>MindDev25 Reversi</h3><p>{t.description}</p><div className="tile-link">{t.play} <ArrowRight size={18}/></div></div></a></section>
 <section className="coming-grid"><article id="tools"><Hammer/><span>02 / {t.tools}</span><h2>{t.toolsHeading}</h2><p>{t.toolsNote}</p></article><article id="creative"><Palette/><span>03 / {t.creative}</span><h2>{t.creativeHeading}</h2><p>{t.creativeNote}</p></article></section></main>
 <footer className="home-footer"><ShieldCheck size={18}/><span>{t.privacy}</span><b>MindDev25 © 2026</b></footer>
 </div>}
